---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    environmnet: development
    name: httpd-deployment
  name: httpd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      name: httpd-pod
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      name: httpd-pod
      labels:
        name: httpd-pod
        environment: development
    spec:
      containers:
      - name: httpd-container
        image: httpd
        ports:
          - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: httpd-service
spec:
  selector:
    name: httpd-pod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
