apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    environmnet: development
    name: jeff-deployment
  name: jeff-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: jeff-pod
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      name: jeff-pod
      labels:
        name: jeff-pod
        environment: development
    spec:
      containers:
      - name: jeff-container
        image: us.gcr.io/g-1575-k8-workshop/jeff:tomato
        ports:
          - containerPort: 80
        resources:
          limits:
            cpu: 64m
            memory: 64Mi
          requests:
            cpu: 32m
            memory: 32Mi
---
kind: Service
apiVersion: v1
metadata:
  name: jeff-service
spec:
  selector:
    name: jeff-pod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
