apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
  labels:
    name: httpd-pod
    environment: development
spec:
  containers:
  - name: httpd-container
    image: httpd
    ports:
      - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: httpd-service
spec:
  selector:
    name: httpd-pod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
