apiVersion: v1
kind: Pod
metadata:
  name: jeff-pod
  labels:
    name: jeff-pod
    environment: development
spec:
  containers:
  - name: jeff-container
    image: briananstett/workshop
    ports:
      - containerPort: 80
    resources:
      limits:
        cpu: 64m
        memory: 64Mi
      requests:
        cpu: 32m
        memory: 32Mi
---
kind: Service
apiVersion: v1
metadata:
  name: jeff-service
spec:
  selector:
    name: jeff-pod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
