apiVersion: v1
kind: Pod
metadata:
  name: jeff-manual-pod
  labels:
    name: jeff-manual-pod
    environment: development
spec:
  containers:
  - name: jeff-manual-container
    image: us.gcr.io/g-1575-k8-workshop/jeff
    ports:
      - containerPort: 80
    resources:
      limits:
        cpu: 64m
        memory: 64Mi
      requests:
        cpu: 32m
        memory: 32Mi

