kind: ConfigMap
apiVersion: v1
metadata:
  annotations:
    {{- include "annotations" . | nindent 4 }}
  labels:
    name: {{ .Release.Name }}-configmap
    {{- include "labels" . | nindent 4 }}
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace}}
data:
  port: {{ required "A valid .Values.container.port entry required!" .Values.container.port | quote }}