kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class | quote }}
    certmanager.k8s.io/cluster-issuer: letsencrypt-production
    external-dns.alpha.kubernetes.io: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    description: "nginx ingress for finished cake"
    {{- include "annotations" . | nindent 4 }}
  labels:
    name: {{ .Release.Name }}-ingress
    {{- include "labels" . | nindent 4 }}
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Release.Namespace}}
spec:
  rules:
  - host: {{ .Values.ingress.host}}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-service
          servicePort: {{ .Values.service.port }}
  tls:
    - hosts:
      - {{ required "A valid .Values.ingress.host entry required!" .Values.ingress.host }}
      secretName: {{ .Release.Name }}-lets-encrypt-cert