apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name}}-rolebinding
  namespace: {{ .Release.Namespace}}
  annotations:
    {{- include "annotations" . | nindent 4 }}
  labels:
    name: {{ .Release.Name}}-rolebinding
    {{- include "labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name}}-role
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name}}-serviceaccount
  namespace: {{ .Release.Namespace}}
