---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    environmnet: development
    name: apache-deployment
  name: apache-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      name: apache-pod
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      name: apache-pod
      labels:
        name: apache-pod
        environment: development
    spec:
      containers:
      - name: apache-container
        image: k8s.gcr.io/hpa-example
        ports:
          - containerPort: 80
        resources:
          requests:
            cpu: 200m
---
kind: Service
apiVersion: v1
metadata:
  name: apache-service
spec:
  selector:
    name: apache-pod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    name: apache-hpa
  name: apache-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: apache-deployment
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
